sql-passes: Resolve schemas for non-schema-qualified cols
If we get a query like:

    SELECT t1.x FROM s1.t1

previously, the implied_tables pass would see that `t1.x` has a
table (`t1`), so skip over it - but then once we were actually making
the nodes for the query, we'd fail because there's no table called `t1`
(it's called `s1.t1`). Now, the implied_tables pass *also* resolves
references in columns to non-schema-qualified tables, by checking to see
if the table can be uniquely resolved and returning a warning if it's
ambiguous, which matches postgresql's behavior:

    localhost/readyset=# select t.x from s1.t, s2.t;
    ERROR:  42P09: table reference "t" is ambiguous
    LINE 1: select t.x from s1.t, s2.t;
                ^
    LOCATION:  scanNameSpaceForRefname, parse_relation.c:199
    Time: 0.407 ms

and also mysql's behavior:

    MySQL [(none)]> select t.x from s1.t, s2.t;
    ERROR 1052 (23000): Column 't.x' in field list is ambiguous

Fixes: ENG-1756
Change-Id: I840d338a6d405d223d045fc421f204f11432f70d
Reviewed-on: https://gerrit.readyset.name/c/readyset/+/3109
Tested-by: Buildkite CI
Reviewed-by: Vlad Krasnov <vlad@readyset.io>