Adapter: Support SHOW READYSET MIGRATION STATUS
Adds a SQL extension to query the status of a migration initiated by
CREATE CACHE CONCURRENTLY.

Release-Note-Core: Adds a `SHOW READYSET MIGRATION STATUS <id>` SQL
  extension to query the status of a migration initiated via `CREATE
  CACHE CONCURRENTLY`. This command will return the status of the
  migration, which is either "Completed", "Pending", or "Failed with
  error: <error>". Executing this statement with an id that has already
  returned a non-pending status (Completed or Failed) will lead to
  undefined behavior.
Change-Id: I28357581ce2c4785b9a1ec1148217d02910184cb
Reviewed-on: https://gerrit.readyset.name/c/readyset/+/5759
Tested-by: Buildkite CI
Reviewed-by: Aspen Smith <aspen@readyset.io>