ops/benchmarks: hotfix minimal benchmark yaml path errors in benchmarks
It looks like some of our recently added benchmarks included a more
complete path than is expected by the benchmark binary, due to the
working directory used by our tests. This seems to be causing the
following error to get thrown by the benchmark binary:

Error: Could not find the file: benchmarks/src/data/minimal/paginate.sql
Change-Id: Ia68cc0a79e7991c36ec12d4b84f5867c4374e900
Reviewed-on: https://gerrit.readyset.name/c/readyset/+/2155
Reviewed-by: Harley Klein <harley@readyset.io>
Reviewed-by: Griffin Smith <griffin@readyset.io>
Tested-by: Buildkite CI